'use strict';
const mongoose = require('mongoose');

const HeroSchema = new mongoose.Schema({
  _id: Number,
  name: String,
  localized_name: String,
  primary_attr: String,
  attack_type: String,
  roles: [String],
  img: String,
  icon: String,
  base_health: Number,
  base_health_regen: Number,
  base_mana: Number,
  base_mana_regen: Number,
  base_armor: Number,
  base_mr: Number,
  base_attack_min: Number,
  base_attack_max: Number,
  base_str: Number,
  base_agi: Number,
  base_int: Number,
  str_gain: Number,
  agi_gain: Number,
  int_gain: Number,
  attack_range: Number,
  projectile_speed: Number,
  attack_rate: Number,
  move_speed: Number,
  turn_rate: Number,
  cm_enabled: Boolean,
  legs: Number,
  pro_win: Number,
  pro_pick: Number,
  hero_id: Number,
  pro_ban: Number,
  '8_pick': Number,
  '8_win': Number,
  '1_pick': Number,
  '1_win': Number,
  '4_pick': Number,
  '4_win': Number,
  '3_pick': Number,
  '3_win': Number,
  '5_pick': Number,
  '5_win': Number,
  '7_pick': Number,
  '7_win': Number,
  '6_pick': Number,
  '6_win': Number,
  '2_pick': Number,
  '2_win': Number,
});

module.exports = mongoose.model('Heroes', HeroSchema);